### ISSUE TITLE
没有工作

### ISSUE THREAD

**Issue by PuerNya** [eebssk1/riru_MPH#1]
我在使用了 米推注册机后 注册了几个 app
工作原理是修改了这几个地方
```
ro.product.brand=Xiaomi
ro.product.manufacturer=Xiaomi
ro.miui.ui.version.code=10
ro.miui.ui.version.name=V12
```
然后切换成了 riru_MPH 也在推送服务里对对应 app 打开了开关，然而并没有起作用呢，没有任何 app 注册上了

**Comment by PuerNya** [comment]
请忽略我的修改历史 md 太久没写了（扶额）

**Comment by eebssk1** [comment]
请重启手机并且在开机前使用``adb logcat MPH:*``开始获取日志。开机后启动任意一个已经在挂钩列表里的app。提供一下日志和系统信息

**Comment by eebssk1** [comment]
另外说一句推送服务里的硬编码的保存地址早已经被弃用了。请手动编辑/data/misc/mph/config/packages

**Comment by eebssk1** [comment]
Closed due to inactivity.
