### ISSUE TITLE
It makes Alipay blocked at start page

### ISSUE THREAD

**Issue by Deleted-Account** [eebssk1/riru_MPH#2]
Device: OnePlus 7 pro
System: Android 10
Env: Riru v25.4.2  MPH v25.1.0 LSPosed v1.3.5 (With MiPush Framework Enhancement Module v1.2) 

I've no idea it's compatible or has conflict with MiPush Frameworke Enhancement Module.
After I installed MPH, Alipay blocked at start page, Coolapk and some other apps had noticeable lag right after I tapped apps' icon

At the very first time I guessed it would be Thanox's issue. Then I disabled its App ops  and Incognito functions. Restarted my cellphone many times. But Alipay still blocked, Coolapk and some other apps still lagged at initiating.

Then I reinstalled XiaoMi_Push_Framework_Fake_Advanced-v2.8 (I modified it  to MIUI 12 as your module's parameters) and disabled MPH, everything came back to normal.

**Comment by eebssk1** [comment]
First make sure you are using riru 25+.

It may be conflicted when used with xposed hooks since the replaced native function may not play well in xposed space.

There's also a possilble case that your Rom changes the related code as the module is based on AOSP.

Please try without using related xposed modules and get logs with tag "MPH".

**Comment by eebssk1** [comment]
I don't know how noticeble the lag is,but if you are cold start app then it is normal to be a bit lag as the hook need to block the process.

**Comment by eebssk1** [comment]
The use of DobbySymbolResolver is a bit expensive too. I'm about to replace it with symbol reference instead.I tested this before and it was working.

**Comment by Deleted-Account** [comment]
> I don't know how noticeable the lag is, but if you are cold start app then it is normal to be a bit lag as the hook need to block the process.

App usually and should be started immediately right after I tap app's icon.
"noticeable lag" means (some of them, not all) apps start with hesitation (lag at Launcher, might also stuck at start page or with black screen).

I installed 19 Xposed modules and 20 Magisk packages.
I've no idea any other modules also have conflict with MPH. 
As your reply, I disabled MiPush Frameworke Enhancement and XiaoMi_Push_Framework_Fake_Advanced-v2.8 in LSPosed and Magisk respectively, re-enabled MPH again. (I assume there's no other app/module that could hook system to be like MIUI).
Rebooted my cellphone but the blocked/lag issue happened again.  : (

I didn't delete any log in Magisk.  It seems no logs about MPH.

**Comment by eebssk1** [comment]
> 
> 
> > I don't know how noticeable the lag is, but if you are cold start app then it is normal to be a bit lag as the hook need to block the process.
> 
> App usually and should be started immediately right after I tap app's icon.
> "noticeable lag" means (some of them, not all) apps start with hesitation (lag at Launcher, might also stuck at start page or with black screen).
> 
> I installed 19 Xposed modules and 20 Magisk packages.
> I've no idea any other modules also have conflict with MPH.
> As your reply, I disabled MiPush Frameworke Enhancement and XiaoMi_Push_Framework_Fake_Advanced-v2.8 in LSPosed and Magisk respectively, re-enabled MPH again. (I assume there's no other app/module that could hook system to be like MIUI).
> Rebooted my cellphone but the blocked/lag issue happened again. : (
> 
> I didn't delete any log in Magisk. It seems no logs about MPH.

Then maybe your Rom changes a lot so the code path is different. There's other Riru module that do the same thing made by real developers ,may be you can use them instead.
The log is not in Magisk, you can catch them simplely with logcat.
The module is strictly AOSP based.I don't have issues on LOS. If you get any devices run it,maybe you can test it for me.

**Comment by eebssk1** [comment]
Pls check the new version v25.3.1.

If it still stuck then i can do nothing, sorry🌝.

**Comment by Deleted-Account** [comment]
> Pls check the new version v25.3.1.
> 
> If it still stuck then i can do nothing, sorry🌝.

re-enabled mph and installed 25.3.1
disabled MiPush Framework Enhancement an XiaoMi Push Framework Fake Advanced
rebooted
...
...
😂stuck as always. 
T_T sayonara, MPH.

**Comment by eebssk1** [comment]
I got this problem during development too. I think this is caused by data pointer in hooker lib not correctly returned to the caller, which make the app stuck at waiting the result.
The code path in your Rom may differ from AOSP, so I can't fix this without the rom source.

**Comment by Deleted-Account** [comment]
> I got this problem during development too. I think this is caused by data pointer in hooker lib not correctly returned to the caller, which make the app stuck at waiting the result.
> The code path in your Rom may differ from AOSP, so I can't fix this without the rom source.

I'm using OnePlus 7pro with Hydrogen OS 10.0.10.GM21.
It seems to be an AOSP like system.

**Comment by eebssk1** [comment]
解决不了 🐎了 哭哭

也有可能单纯是dobby的问题，之前看到一个模块也开始分有无dobby版了，看来dobby兼容性也有一定问题。

**Comment by eebssk1** [comment]
The caller of the functions may expect a full(or different) prop object instead of the compact one declared in the module(incompatible), which may differ from the rom's and cause  such problem.This will not be resolved since it does not follow the aosp.


Since there's no clean clue to debug the issue,I'll closs this anyway.

**Comment by Deleted-Account** [comment]
I tried your module last night.
And I found that only CoolApk and Alipay have stuck issue.
Other apps run properly on my device. Em...

**Comment by eebssk1** [comment]
Ah...Interesting...
