### ISSUE TITLE
一个疑惑

### ISSUE THREAD

**Issue by nekomiya-hinata** [eebssk1/riru_MPH#3]
为啥最新的Releases包大小一下变得这么大呢，在这里有些疑惑，希望能够得到解答(●ˇ∀ˇ●)

**Comment by eebssk1** [comment]
淦，才发现dobby的演示程序被打包进去了。。gradle总是把这东西作为默认目标编译进去我也是佛了

**Comment by nekomiya-hinata** [comment]
> 淦，才发现dobby的演示程序被打包进去了。。gradle总是把这东西作为默认目标编译进去我也是佛了

指的是多出来的android_example这个文件么

**Comment by eebssk1** [comment]
> 
> 
> > 淦，才发现dobby的演示程序被打包进去了。。gradle总是把这东西作为默认目标编译进去我也是佛了
> 
> 指的是多出来的android_example这个文件么

是的

**Comment by nekomiya-hinata** [comment]
> > > 淦，才发现dobby的演示程序被打包进去了。。gradle总是把这东西作为默认目标编译进去我也是佛了
> > 
> > 
> > 指的是多出来的android_example这个文件么
> 
> 是的

好的，了解了，希望大佬能够在下个Releases解决下吧( •̀ ω •́ )✧
