### ISSUE TITLE
请问如何使用呢？

### ISSUE THREAD

**Issue by zzzop** [eebssk1/riru_MPH#4]
我现在安装了推送服务的apk还有您这个模块，但是应用都不注册，data/misc/mph/config/packages这里的包名文件是存在就好，还是需要编辑内容

**Comment by eebssk1** [comment]
报名存在就行
参考 https://github.com/eebssk1/riru_MPH/blob/master/template/magisk_module/customize.sh

**Comment by zzzop** [comment]
> 报名存在就行 参考 https://github.com/eebssk1/riru_MPH/blob/master/template/magisk_module/customize.sh

framework推送服务的app里面需要打开“全局伪装miui选项吗”

**Comment by eebssk1** [comment]
> 
> 
> > 报名存在就行 参考 https://github.com/eebssk1/riru_MPH/blob/master/template/magisk_module/customize.sh
> 
> framework推送服务的app里面需要打开“全局伪装miui选项吗”

和推送服务无关，除非你用的是我自己修改过和riru_MPH配套的推送服务(已失传且无法再次构建)。所以只能自己手动往配置目录丢包名

**Comment by zzzop** [comment]
> > > 报名存在就行 参考 https://github.com/eebssk1/riru_MPH/blob/master/template/magisk_module/customize.sh
> > 
> > 
> > framework推送服务的app里面需要打开“全局伪装miui选项吗”
> 
> 和推送服务无关，除非你用的是我自己修改过和riru_MPH配套的推送服务(已失传且无法再次构建)。所以只能自己手动往配置目录丢包名

好的，明白了，那我的应用不注册看来是另有原因，搞不懂了

**Comment by eebssk1** [comment]
请确保使用的是最新版riru并且magisk没有开启新的zygisk功能。
